### ISSUE TITLE
Deployment failing with multiple issues. one of them is - cannot find module 'composer-connector-hlfv11'

### ISSUE THREAD

**Issue by sachinjha** [IBM-Blockchain/toolchain-sample-vehicle-manufacture#10]
----- create ca card ----- 

 --- Pushing the Vehicle manufacture application 'vehicle-manufacture-org2-201804031' ---
Creating app vehicle-manufacture-org2-201804031 in org xxxx@in.ibm.com / space api-demo as xxx@in.ibm.com...
Creating app composer-rest-server-vehicle-manufacture-org2-201804031 in org xxx@in.ibm.com / space api-demo as xxx@in.ibm.com...
Creating app composer-playground-vehicle-manufacture-org2-201804031 in org xxx@in.ibm.com / space api-demo as xxx@in.ibm.com...
OK

OK

OK

Successfully created business network card file to 
	Output file: ca.card

Command succeeded

Creating route composer-playground-vehicle-manufacture-org2-201804031.mybluemix.net...
Creating route vehicle-manufacture-org2-201804031.mybluemix.net...
Creating route composer-rest-server-vehicle-manufacture-org2-201804031.mybluemix.net...
OK

Binding composer-rest-server-vehicle-manufacture-org2-201804031.mybluemix.net to composer-rest-server-vehicle-manufacture-org2-201804031...
OK

Binding vehicle-manufacture-org2-201804031.mybluemix.net to vehicle-manufacture-org2-201804031...
OK

Error: Failed to load connector module "composer-connector-hlfv11" for connection type "hlfv11". **Cannot find module 'composer-connector-hlfv11'-**Cannot find module 'composer-connector-hlfv11'-Cannot find module 'composer-connector-hlfv11'-Cannot find module 'composer-connector-hlfv11'-Cannot find module 'composer-connector-hlfv11'-Cannot find module 'composer-connector-hlfv11'-Cannot find module 'composer-connector-hlfv11'-Cannot find module 'composer-connector-hlfv11'-Cannot find module 'composer-connector-hlfv11'-Cannot find module 'composer-connector-hlfv11'
Command failed

 --- Uh oh something failed... ---
OK

Binding composer-playground-vehicle-manufacture-org2-201804031.mybluemix.net to composer-playground-vehicle-manufacture-org2-201804031...
OK

**shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory**
FAILED
Error read/writing config:  getwd: no such file or directory
Setting env variable 'NODE_CONFIG' to '{"composer":{"wallet":{"type":"@ampretia/composer-wallet-cloudant","desc":"Uses cloud wallet","options":{
  "host": "2e9c2fc5-dd55-4c14-8984-3586f90bbcbd-bluemix.cloudant.com",
  "password": "5c429fa5cd54d8bfb76d9d7e7ddc4faf5e5338e2fda63d4627a2c1abf1a2d51b",
  "port": 443,
  "url": "https://2e9c2fc5-dd55-4c14-8984-3586f90bbcbd-bluemix:5c429fa5cd54d8bfb76d9d7e7ddc4faf5e5338e2fda63d4627a2c1abf1a2d51b@2e9c2fc5-dd55-4c14-8984-3586f90bbcbd-bluemix.cloudant.com",
  "username": "2e9c2fc5-dd55-4c14-8984-3586f90bbcbd-bluemix",
  "database": "vehicle-manufacture-org2-201804031"
}}}}' for app composer-rest-server-vehicle-manufacture-org2-201804031 in org xxx@in.ibm.com / space api-demo as xxx@in.ibm.com...
OK
TIP: Use 'cf restage composer-rest-server-vehicle-manufacture-org2-201804031' to ensure your env variable changes take effect
Tue Apr  3 12:11:58 UTC 2018

----- Pushed REST server ----- 
OK

Tue Apr  3 12:12:01 UTC 2018

 --- Pushed the Vehicle manufacture application 'vehicle-manufacture-org2-201804031' ---

Finished: FAILED

**Comment by dshuffma-ibm** [comment]
the `hlfv11` part of the error should be resolved now.  if you refresh/get a new connection profile it should have `"x-type": "hlfv1"` not `hlfv11`

**Comment by cazfletch** [comment]
closing as this looks to be fixed
